#!/usr/bin/env bash
# script that configure Nginx redirect
# /redirect_me is redirecting to another domain

apt-get update
apt-get -y --force-yes install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://moz.com/learn/seo/redirection permanent;' /etc/nginx/sitesavailable/default
service nginx restart

