#!/usr/bin/env bash
# script that configure Nginx redirect
# /redirect_me is redirecting to another domain

apt-get update
apt-get -y --force-yes install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://moz.com/learn/seo/redirection permanent;' /etc/nginx/sites-available/default
echo "Cest n'est pas une page" ? /var/www/html/404.html
sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\n root /var/www/html;\nintenal;\n}' /etc/nginx/sites-available/default
service nginx restart

