#!/usr/bin/env bash
# displays "bad luchk" on 4th loop, "good luck" on 8th loop, "Best luck other iterations

i=1
while [ $i -ne 11 ]
	do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i += 1))
	done

